[versions]
agp = "8.7.3"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
material = "1.12.0"
constraintlayout = "2.2.0"
lifecycle = "2.8.7"
navigationFragment = "2.8.4"
navigationUi = "2.8.4"
fragment = "1.8.5"
appcompat = "1.7.0"
material3 = "1.3.1"
material3WindowSizeClass = "1.3.1"
viewpager2 = "1.1.0"
okhttp3 = "5.0.0-alpha.14"
gson = "2.11.0"
retrofit2 = "2.11.0"
retrofit2ConverterGson = "2.11.0"
retrofit2ConverterScalars = "2.11.0"
okhttp3LoggingInterceptor = "5.0.0-alpha.14"
prettytime = "5.0.8.Final"
colorpickerview = "2.3.0"
notiesMarkwon = "4.6.2"
glide = "4.16.0"
breadcrumbs = "0.2.9"
roomDB = "2.6.1"
biometric = "1.1.0"
browser = "1.8.0"
codeview = "1.3.9"
annotation = "1.9.1"
urlbuilder = "2.0.9"
swiperefreshlayout = "1.1.0"
desugar_jdk_libs = "2.1.3"
emoji-java = "v5.1.2"
android-svg = "1.4"
android-gif-drawable = "1.2.29"
stormpot = "2.4.2"
splashscreen = "1.0.1"
photoview = "2.3.0"
commonsio = "2.16.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3WindowSizeClass" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2ConverterGson" }
retrofit2-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit2ConverterScalars" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3LoggingInterceptor" }
prettytime = { group = "org.ocpsoft.prettytime", name = "prettytime", version.ref = "prettytime" }
colorpickerview = { group = "com.github.skydoves", name = "colorpickerview", version.ref = "colorpickerview" }
notiesmarkwon-core = { group = "io.noties.markwon", name = "core", version.ref = "notiesMarkwon" }
notiesmarkwon-ext-latex = { group = "io.noties.markwon", name = "ext-latex", version.ref = "notiesMarkwon" }
notiesmarkwon-ext-strikethrough = { group = "io.noties.markwon", name = "ext-strikethrough", version.ref = "notiesMarkwon" }
notiesmarkwon-ext-tables = { group = "io.noties.markwon", name = "ext-tables", version.ref = "notiesMarkwon" }
notiesmarkwon-ext-tasklist = { group = "io.noties.markwon", name = "ext-tasklist", version.ref = "notiesMarkwon" }
notiesmarkwon-html = { group = "io.noties.markwon", name = "html", version.ref = "notiesMarkwon" }
notiesmarkwon-image = { group = "io.noties.markwon", name = "image", version.ref = "notiesMarkwon" }
notiesmarkwon-image-glide = { group = "io.noties.markwon", name = "image-glide", version.ref = "notiesMarkwon" }
notiesmarkwon-linkify = { group = "io.noties.markwon", name = "linkify", version.ref = "notiesMarkwon" }
notiesmarkwon-recycler = { group = "io.noties.markwon", name = "recycler", version.ref = "notiesMarkwon" }
notiesmarkwon-recycler-table = { group = "io.noties.markwon", name = "recycler-table", version.ref = "notiesMarkwon" }
notiesmarkwon-ext-simple = { group = "io.noties.markwon", name = "simple-ext", version.ref = "notiesMarkwon" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
breadcrumbs = { group = "com.github.HamidrezaAmz", name = "BreadcrumbsView", version.ref = "breadcrumbs" }
room-db = { group = "androidx.room", name = "room-runtime", version.ref = "roomDB" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomDB" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
codeview = { group = "io.github.amrdeveloper", name = "codeview", version.ref = "codeview" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
urlbuilder = { group = "io.mikael", name = "urlbuilder", version.ref = "urlbuilder" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
emoji-java = { group = "org.codeberg.gitnex-garage", name = "emoji-java", version.ref = "emoji-java" }
android-svg = { group = "com.caverock", name = "androidsvg-aar", version.ref = "android-svg" }
android-gif-drawable = { group = "pl.droidsonroids.gif", name = "android-gif-drawable", version.ref = "android-gif-drawable" }
stormpot = { group = "com.github.chrisvest", name = "stormpot", version.ref = "stormpot" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsio" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
